"use client"

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#1a1a1a",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 30,
  },
  logo: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#0d9488",
  },
  receiptTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#0d9488",
    textAlign: "right",
  },
  receiptNumber: {
    fontSize: 10,
    color: "#6b7280",
    textAlign: "right",
    marginTop: 4,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    marginVertical: 20,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  label: {
    color: "#6b7280",
    fontSize: 10,
  },
  value: {
    fontSize: 10,
    fontWeight: "bold",
  },
  sectionTitle: {
    fontSize: 9,
    fontWeight: "bold",
    color: "#9ca3af",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 20,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 2,
    borderTopColor: "#0d9488",
    paddingTop: 10,
    marginTop: 10,
  },
  totalLabel: {
    fontSize: 12,
    fontWeight: "bold",
  },
  totalValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#0d9488",
  },
  footer: {
    textAlign: "center",
    color: "#9ca3af",
    fontSize: 8,
    marginTop: 40,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 15,
  },
})

interface ReceiptPDFProps {
  receiptNumber: string
  date: string
  userName: string
  userEmail: string
  amount: number
  currency: string
  planName: string
  paymentMethod: string
  orderId: string
}

export function ReceiptPDF({
  receiptNumber,
  date,
  userName,
  userEmail,
  amount,
  currency,
  planName,
  paymentMethod,
  orderId,
}: ReceiptPDFProps) {
  const formatAmount = (val: number) =>
    new Intl.NumberFormat("en-US", {
      style: "currency",
      currency,
    }).format(val)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.logo}>CreatorDeal</Text>
            <Text style={{ fontSize: 9, color: "#6b7280", marginTop: 4 }}>
              Sponsorship Management for Creators
            </Text>
          </View>
          <View>
            <Text style={styles.receiptTitle}>RECEIPT</Text>
            <Text style={styles.receiptNumber}>{receiptNumber}</Text>
          </View>
        </View>

        <View style={styles.divider} />

        {/* Transaction Details */}
        <Text style={styles.sectionTitle}>Transaction Details</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Date</Text>
          <Text style={styles.value}>{date}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment Method</Text>
          <Text style={styles.value}>{paymentMethod}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Order ID</Text>
          <Text style={styles.value}>{orderId}</Text>
        </View>

        {/* Bill To */}
        <Text style={styles.sectionTitle}>Bill To</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Name</Text>
          <Text style={styles.value}>{userName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Email</Text>
          <Text style={styles.value}>{userEmail}</Text>
        </View>

        {/* Line Items */}
        <Text style={styles.sectionTitle}>Items</Text>
        <View style={styles.row}>
          <Text style={[styles.label, { flex: 1 }]}>{planName} (Monthly Subscription)</Text>
          <Text style={styles.value}>{formatAmount(amount)}</Text>
        </View>

        {/* Total */}
        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Total Paid</Text>
          <Text style={styles.totalValue}>{formatAmount(amount)}</Text>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          This receipt confirms your payment to CreatorDeal.{"\n"}
          For questions, contact support@creatordeal.app{"\n"}
          Generated by CreatorDeal
        </Text>
      </Page>
    </Document>
  )
}
