"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Plus, FileText, Send, CheckCircle, Clock, AlertCircle, Download, Eye } from "lucide-react"

const statusConfig = {
  draft: { label: "Draft", color: "bg-muted text-muted-foreground", icon: FileText },
  sent: { label: "Sent", color: "bg-blue-100 text-blue-700", icon: Send },
  viewed: { label: "Viewed", color: "bg-yellow-100 text-yellow-700", icon: Clock },
  paid: { label: "Paid", color: "bg-green-100 text-green-700", icon: CheckCircle },
  overdue: { label: "Overdue", color: "bg-red-100 text-red-700", icon: AlertCircle },
  cancelled: { label: "Cancelled", color: "bg-gray-100 text-gray-700", icon: FileText },
}

const initialInvoices = [
  {
    id: "1",
    invoice_number: "INV-2026-001",
    amount: 5000,
    status: "paid",
    due_date: "2026-06-15",
    deal: { title: "Nike Summer Campaign", brand: { name: "Nike" } },
  },
  {
    id: "2",
    invoice_number: "INV-2026-002",
    amount: 8000,
    status: "sent",
    due_date: "2026-07-01",
    deal: { title: "Apple Product Review", brand: { name: "Apple" } },
  },
  {
    id: "3",
    invoice_number: "INV-2026-003",
    amount: 12000,
    status: "overdue",
    due_date: "2026-06-20",
    deal: { title: "Samsung Galaxy Launch", brand: { name: "Samsung" } },
  },
  {
    id: "4",
    invoice_number: "INV-2026-004",
    amount: 15000,
    status: "draft",
    due_date: "2026-07-15",
    deal: { title: "Tesla Model Y Review", brand: { name: "Tesla" } },
  },
]

function InvoicePreview({ invoice }: { invoice: typeof initialInvoices[0] }) {
  return (
    <div className="bg-white p-8 rounded-lg shadow-inner max-w-md mx-auto">
      <div className="text-center mb-8">
        <h1 className="text-2xl font-bold text-gray-800">CreatorDeal</h1>
        <p className="text-sm text-gray-500">Invoice</p>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-6">
        <div>
          <p className="text-xs text-gray-500 uppercase">From</p>
          <p className="font-medium">John Doe</p>
          <p className="text-sm text-gray-600">john@example.com</p>
        </div>
        <div className="text-right">
          <p className="text-xs text-gray-500 uppercase">To</p>
          <p className="font-medium">{invoice.deal.brand.name}</p>
          <p className="text-sm text-gray-600">contact@{invoice.deal.brand.name.toLowerCase()}.com</p>
        </div>
      </div>

      <div className="border-t border-b py-4 mb-6">
        <div className="flex justify-between mb-2">
          <span className="text-sm text-gray-500">Invoice #</span>
          <span className="font-medium">{invoice.invoice_number}</span>
        </div>
        <div className="flex justify-between mb-2">
          <span className="text-sm text-gray-500">Deal</span>
          <span className="font-medium">{invoice.deal.title}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-sm text-gray-500">Due Date</span>
          <span className="font-medium">
            {new Date(invoice.due_date).toLocaleDateString("en-US", {
              month: "long",
              day: "numeric",
              year: "numeric",
            })}
          </span>
        </div>
      </div>

      <div className="mb-6">
        <div className="flex justify-between text-sm text-gray-500 mb-2">
          <span>Description</span>
          <span>Amount</span>
        </div>
        <div className="flex justify-between">
          <span>{invoice.deal.title}</span>
          <span className="font-medium">${invoice.amount.toLocaleString()}</span>
        </div>
      </div>

      <div className="border-t pt-4">
        <div className="flex justify-between text-lg font-bold">
          <span>Total</span>
          <span className="text-primary">${invoice.amount.toLocaleString()}</span>
        </div>
      </div>

      <div className="mt-8 text-center text-xs text-gray-400">
        <p>Thank you for your business!</p>
        <p className="mt-1">Generated by CreatorDeal</p>
      </div>
    </div>
  )
}

export default function InvoicesPage() {
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [invoices, setInvoices] = useState(initialInvoices)
  const [previewInvoice, setPreviewInvoice] = useState<typeof initialInvoices[0] | null>(null)
  const [newInvoice, setNewInvoice] = useState({
    deal_title: "",
    brand_name: "",
    amount: "",
    due_date: "",
  })

  const totalPending = invoices
    .filter((inv) => !["paid", "cancelled"].includes(inv.status))
    .reduce((sum, inv) => sum + inv.amount, 0)

  const totalPaid = invoices
    .filter((inv) => inv.status === "paid")
    .reduce((sum, inv) => sum + inv.amount, 0)

  const handleCreateInvoice = () => {
    if (!newInvoice.deal_title || !newInvoice.brand_name || !newInvoice.amount) return

    const invoice = {
      id: String(Date.now()),
      invoice_number: `INV-2026-${String(invoices.length + 1).padStart(3, "0")}`,
      amount: Number(newInvoice.amount),
      status: "draft",
      due_date: newInvoice.due_date || new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      deal: {
        title: newInvoice.deal_title,
        brand: { name: newInvoice.brand_name },
      },
    }

    setInvoices([invoice, ...invoices])
    setNewInvoice({ deal_title: "", brand_name: "", amount: "", due_date: "" })
    setIsDialogOpen(false)
  }

  const sendInvoice = (id: string) => {
    setInvoices(
      invoices.map((inv) => (inv.id === id ? { ...inv, status: "sent" } : inv))
    )
  }

  const handlePrint = () => {
    window.print()
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold">Invoices</h2>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" /> Create Invoice
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Create New Invoice</DialogTitle>
              <DialogDescription>
                Generate an invoice for a completed deal.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="deal_title">Deal Title</Label>
                  <Input
                    id="deal_title"
                    placeholder="Nike Summer Campaign"
                    value={newInvoice.deal_title}
                    onChange={(e) => setNewInvoice({ ...newInvoice, deal_title: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="brand_name">Brand</Label>
                  <Input
                    id="brand_name"
                    placeholder="Nike"
                    value={newInvoice.brand_name}
                    onChange={(e) => setNewInvoice({ ...newInvoice, brand_name: e.target.value })}
                  />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="amount">Amount ($)</Label>
                  <Input
                    id="amount"
                    type="number"
                    placeholder="5000"
                    value={newInvoice.amount}
                    onChange={(e) => setNewInvoice({ ...newInvoice, amount: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="due_date">Due Date</Label>
                  <Input
                    id="due_date"
                    type="date"
                    value={newInvoice.due_date}
                    onChange={(e) => setNewInvoice({ ...newInvoice, due_date: e.target.value })}
                  />
                </div>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
                Cancel
              </Button>
              <Button onClick={handleCreateInvoice}>
                Create Invoice
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      {/* Stats */}
      <div className="grid gap-4 md:grid-cols-2">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Pending</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">${totalPending.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground">
              {invoices.filter((inv) => !["paid", "cancelled"].includes(inv.status)).length} invoices pending
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Paid</CardTitle>
            <CheckCircle className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">${totalPaid.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground">
              {invoices.filter((inv) => inv.status === "paid").length} invoices paid
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Invoices Table */}
      <Card>
        <CardHeader>
          <CardTitle>All Invoices</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {invoices.map((invoice) => {
              const status = statusConfig[invoice.status as keyof typeof statusConfig]
              const StatusIcon = status.icon
              return (
                <div
                  key={invoice.id}
                  className="flex items-center justify-between rounded-lg border p-4"
                >
                  <div className="flex items-center gap-4">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                      <FileText className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <p className="font-medium">{invoice.invoice_number}</p>
                      <p className="text-sm text-muted-foreground">
                        {invoice.deal.title} • {invoice.deal.brand.name}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-6">
                    <div className="text-right">
                      <p className="font-medium">
                        ${invoice.amount.toLocaleString()}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        Due {new Date(invoice.due_date).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                      </p>
                    </div>
                    <span
                      className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-xs font-medium ${status.color}`}
                    >
                      <StatusIcon className="h-3 w-3" />
                      {status.label}
                    </span>
                    <div className="flex gap-2">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => setPreviewInvoice(invoice)}
                      >
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="sm">
                        <Download className="h-4 w-4" />
                      </Button>
                      {invoice.status === "draft" && (
                        <Button size="sm" onClick={() => sendInvoice(invoice.id)}>
                          <Send className="mr-1 h-4 w-4" /> Send
                        </Button>
                      )}
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </CardContent>
      </Card>

      {/* Invoice Preview Dialog */}
      <Dialog open={!!previewInvoice} onOpenChange={() => setPreviewInvoice(null)}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Invoice Preview</DialogTitle>
            <DialogDescription>
              Preview how your invoice will look to the brand.
            </DialogDescription>
          </DialogHeader>
          {previewInvoice && <InvoicePreview invoice={previewInvoice} />}
          <DialogFooter>
            <Button variant="outline" onClick={() => setPreviewInvoice(null)}>
              Close
            </Button>
            <Button onClick={handlePrint}>
              <Download className="mr-2 h-4 w-4" /> Print / Save PDF
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
